stages:
  - deploy

deploy_test:
  stage: deploy
  tags:
    - node
  only:
    - master
    - test
  cache:
    key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
  before_script:
    - export MONGODB_URL="mongodb://webedit:fxshop123abc@localhost:27017/fxshop_test"
    - export REDIS_HOST="127.0.0.1"
    - export NODE_ENV="production"
    - export INDEX_PAGE_FILE_LOCATION="/data/apps/fxshop-h5/test/index.html"
    - export MCHT_INDEX_PAGE_FILE_LOCATION="/data/apps/fxshop-merchant/test/index.html"
    - export FX_ORDER_PAYING_LIST="fx_order_paying_list_test"
    - export TICKET_QRCODE_PATH="/data/apps/fxshop-backend/test/qrcode"
  script:
    - npm --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist install
    - forever restart ./app/index.js
